Repository wazo-platform/wazo-calld, pull requests merged in 2020-09, with the labels that each got.

#127 Pull request for WAZO-1955-adhoc-conference-connectedline-update
  integration_tests/suite/test_adhoc_conferences.py
  wazo_calld/plugins/adhoc_conferences/stasis.py
Labels: auto-merge

#128 dial_mobile: automatically hang up channel left alone
  wazo_calld/plugins/dial_mobile/services.py
  wazo_calld/plugins/dial_mobile/stasis.py
  wazo_calld/plugins/dial_mobile/tests/test_stasis.py
Labels: mergeit

#113 WAZO-1913 - Pjsip
  integration_tests/suite/test_endpoints_bus_consume.py
  wazo_calld/plugins/endpoints/bus.py
  wazo_calld/plugins/endpoints/services.py
  wazo_calld/plugins/endpoints/tests/test_bus.py
  wazo_calld/plugins/endpoints/tests/test_services.py
Labels: mergeit

#126 adhoc conferences: forbid adding same participant
  integration_tests/suite/test_adhoc_conferences.py
  wazo_calld/plugins/adhoc_conferences/exceptions.py
  wazo_calld/plugins/adhoc_conferences/services.py
Labels: mergeit

#129 Pull request for WAZO-1936-call-line-id
  CHANGELOG.md
  integration_tests/suite/helpers/bus.py
  integration_tests/suite/helpers/constants.py
  integration_tests/suite/test_calls.py
  integration_tests/suite/test_calls_bus_consume.py
  wazo_calld/plugin_helpers/ari_.py
  wazo_calld/plugins/calls/api.yml
  wazo_calld/plugins/calls/call.py
  wazo_calld/plugins/calls/schemas.py
  wazo_calld/plugins/calls/services.py
Labels: mergeit

#125 Pull request for WAZO-1929-adhoc-conference-refactor
  integration_tests/Makefile
  integration_tests/suite/helpers/base.py
  integration_tests/suite/test_adhoc_conferences.py
  integration_tests/suite/test_calls.py
  integration_tests/suite/test_conferences.py
  integration_tests/suite/test_fax.py
  integration_tests/suite/test_relocates.py
  integration_tests/suite/test_voicemail.py
  wazo_calld/plugins/adhoc_conferences/api.yml
  wazo_calld/plugins/adhoc_conferences/services.py
  wazo_calld/plugins/adhoc_conferences/stasis.py
Labels: auto-merge, mergeit

#130 mobile push notification: send video information
  integration_tests/suite/test_push_mobile.py
  wazo_calld/plugins/mobile/bus_consume.py
Labels: mergeit

#131 adhoc conference: fix race condition during test
  integration_tests/suite/test_adhoc_conferences.py
  wazo_calld/plugin_helpers/ari_.py
  wazo_calld/plugins/adhoc_conferences/stasis.py
Labels: mergeit
