Repository wazo-platform/wazo-calld, pull requests merged in 2020-02, with the labels that each got.

#70 Add werkzeug dependency
  debian/control
  requirements.txt
Labels: auto-merge

#69 calls: add call_answered event
  integration_tests/suite/helpers/bus.py
  integration_tests/suite/test_calls_bus_consume.py
  wazo_calld/plugins/calls/bus_consume.py
  wazo_calld/plugins/calls/event.py
  wazo_calld/plugins/calls/notifier.py
Labels: mergeit

#72 WAZO-1594 calls: allow ringing all lines of a user when making an 'originate' r…
  integration_tests/suite/helpers/calld.py
  integration_tests/suite/test_calls.py
  wazo_calld/plugins/calls/api.yml
  wazo_calld/plugins/calls/schemas.py
  wazo_calld/plugins/calls/services.py
Labels: mergeit

#73 WAZO-1599 dial_mobile: make the caller channel ring
  wazo_calld/plugins/dial_mobile/services.py
  wazo_calld/plugins/dial_mobile/tests/test_services.py
Labels: mergeit

#74 WAZO-1337 : add auto-answer headers to relocates and calls
  integration_tests/suite/helpers/calld.py
  integration_tests/suite/test_calls.py
  wazo_calld/plugin_helpers/ari_.py
  wazo_calld/plugins/calls/api.yml
  wazo_calld/plugins/calls/schemas.py
  wazo_calld/plugins/calls/services.py
  wazo_calld/plugins/relocates/api.yml
  wazo_calld/plugins/relocates/http.py
  wazo_calld/plugins/relocates/relocate.py
  wazo_calld/plugins/relocates/schemas.py
  wazo_calld/plugins/relocates/services.py
  wazo_calld/plugins/relocates/state.py
  wazo_calld/plugins/switchboards/services.py
Labels: mergeit

#75 changelog: update 20.03
  CHANGELOG.md
Labels: auto-merge, mergeit

#76 relocates: wait for relocate event before starting test
  integration_tests/suite/test_relocates.py
Labels: mergeit
